openapi: 3.0.0
info:
  title: Nama Aplikasi
  description: Deskripsi Aplika
  version: 1.0.0
servers:
  - url: http://localhost:3301/api/v1

tags:
  - name: Hotels
    description: Hotels CRUD route
  - name: Reservations
    description: Hotel reservations proses
paths:
  /hotels:
    get:
      summary: Get list of hotels
      description: Retrieve a list of hotels from the database.
      tags: [Hotels]
      responses:
        "200":
          description: Successfully retrieved the list of hotels.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Hotel"
        "404":
          description: Hotels not found.
        "500":
          description: Internal server error.

  /reservations/user/{user_id}:
    get:
      summary: user reservations list
      description: Retrieve a list of reservations from the database.
      tags: [Reservations]
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          description: ID for user reservation
          required: true
      responses:
        "200":
          description: return list data reservation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Reservation"
        "404":
          description: Hotels not found.
        "500":
          description: Internal server error.
components:
  schemas:
    Hotel:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the hotel
        name:
          type: string
          description: Name of the hotel
        address:
          type: string
          description: Address of the hotel
        city:
          type: string
          description: City where the hotel is locate
        country:
          type: string
          description: Country where the hotel is located
        rating:
          type: number
          description: Rating of the hotel
    Reservation:
      type: object
      properties:
        _id:
          type: string
          description: id reservation
        reservation_code:
          type: string
          description: code reservation
        total_price:
          type: integer
          description: total reservation price
        date_checkin:
          type: string
          format: date
          description: date checkin reservation (format= yyyy-MM-dd)
        date_checkout:
          type: string
          format: date
          description: date checkout reservation (format= yyyy-MM-dd)
        room_id:
          type: string
          description: room_id for conected the room reservation
        pay:
          type: boolean
          description: status pay true or false
        user_id:
          type: string
          description: user reservation
