name: Pre-Deploy

on: ['push']

jobs:
  running-testing:
    name: Running Testing Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: action/checkout@v2
      - name: Set up Node.js
        uses: action/setup-node@v2
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      
